name: 'staging'

on:
  workflow_run:
    workflows: ['lint and tests']
    branches: [main,feature/semver2]
    types:
      - completed
  workflow_dispatch:

env:
  KEYSTORE_PW: ${{ secrets.KEYSTORE_PW }}
  KEYSTORE: ${{ secrets.KEYSTORE }}
  SA_JSON_KEY: ${{ secrets.SA_JSON_KEY }}
  ALIAS: ${{ secrets.ALIAS }}
  ALIAS_PW: ${{ secrets.ALIAS_PW }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
  APP_VERSION_NAME: ${{ secrets.APP_VERSION_NAME }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_STG }}
  CI_PIPELINE_ID: ${{ github.run_number }}
  CI_COMMIT_BEFORE_SHA: ${{ github.event.before }}
  APP_PACKAGE_NAME: ${{ secrets.APP_PACKAGE_NAME }}
  BUILD_TASK: "assemble"
  BUILD_TYPE: "debug"
  CI_ENVIRONMENT_NAME: ${{ github.workflow }}
  SEMVER: "true"
  FLAVOR_TYPE: "beta"
  GIT_REMOTE: "https://${{ secrets.BASEAUTH }}@github.com:maddevsio/android-ci-cd.git"

jobs:
  staging_firebase:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch' && github.event.workflow_run.conclusion != 'success') }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-

      - uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: true
      - run: echo ${{steps.tag.outputs.tag}}

      - run: |
              echo $KEYSTORE | base64 -d -i > /tmp/my-release-key.keystore
              echo $SA_JSON_KEY | base64 -d -i > key_firebase.json
              echo $GOOGLE_SERVICES_JSON | base64 -d -i > app/google-services.json
              bundle exec fastlane firebase_distribution
